# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/z_turn.bd
# Block Designs: The module: 'z_turn' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_processing_system7_0_0/z_turn_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_processing_system7_0_0 || ORIG_REF_NAME==z_turn_processing_system7_0_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_xlconcat_0_0/z_turn_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xlconcat_0_0 || ORIG_REF_NAME==z_turn_xlconcat_0_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_ps_7_axi_periph_0/z_turn_ps_7_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_ps_7_axi_periph_0 || ORIG_REF_NAME==z_turn_ps_7_axi_periph_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_rst_ps_7_166M_0 || ORIG_REF_NAME==z_turn_rst_ps_7_166M_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_ps_7_axi_periph_1/z_turn_ps_7_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_ps_7_axi_periph_1 || ORIG_REF_NAME==z_turn_ps_7_axi_periph_1}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset1_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_1_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_3_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_3_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_util_vector_logic_0_0/z_turn_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_util_vector_logic_0_0 || ORIG_REF_NAME==z_turn_util_vector_logic_0_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_util_vector_logic_0_1/z_turn_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_util_vector_logic_0_1 || ORIG_REF_NAME==z_turn_util_vector_logic_0_1}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_util_vector_logic_1_0/z_turn_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_util_vector_logic_1_0 || ORIG_REF_NAME==z_turn_util_vector_logic_1_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_xlconcat_0_1/z_turn_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xlconcat_0_1 || ORIG_REF_NAME==z_turn_xlconcat_0_1}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_xlconcat_0_2/z_turn_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xlconcat_0_2 || ORIG_REF_NAME==z_turn_xlconcat_0_2}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_xlconcat_1_0/z_turn_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xlconcat_1_0 || ORIG_REF_NAME==z_turn_xlconcat_1_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_0_0/z_turn_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_clk_wiz_0_0 || ORIG_REF_NAME==z_turn_clk_wiz_0_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_axi_i2s_adi_0_0/z_turn_axi_i2s_adi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_axi_i2s_adi_0_0 || ORIG_REF_NAME==z_turn_axi_i2s_adi_0_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_1_0/z_turn_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_clk_wiz_1_0 || ORIG_REF_NAME==z_turn_clk_wiz_1_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_xbar_0/z_turn_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xbar_0 || ORIG_REF_NAME==z_turn_xbar_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_ultrasonicShiftControl_0_0/z_turn_ultrasonicShiftControl_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_ultrasonicShiftControl_0_0 || ORIG_REF_NAME==z_turn_ultrasonicShiftControl_0_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_ultrasonicAXItoPWM_0_1/z_turn_ultrasonicAXItoPWM_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_ultrasonicAXItoPWM_0_1 || ORIG_REF_NAME==z_turn_ultrasonicAXItoPWM_0_1}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_auto_pc_0/z_turn_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_auto_pc_0 || ORIG_REF_NAME==z_turn_auto_pc_0}]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_processing_system7_0_0/z_turn_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_processing_system7_0_0 || ORIG_REF_NAME==z_turn_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_rst_ps_7_166M_0 || ORIG_REF_NAME==z_turn_rst_ps_7_166M_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_rst_ps_7_166M_0 || ORIG_REF_NAME==z_turn_rst_ps_7_166M_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset1_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset1_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_1_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_1_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_3_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_3_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_3_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_3_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_0_0/z_turn_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_clk_wiz_0_0 || ORIG_REF_NAME==z_turn_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_0_0/z_turn_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_clk_wiz_0_0 || ORIG_REF_NAME==z_turn_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_0_0/z_turn_clk_wiz_0_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_1_0/z_turn_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_clk_wiz_1_0 || ORIG_REF_NAME==z_turn_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_1_0/z_turn_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_clk_wiz_1_0 || ORIG_REF_NAME==z_turn_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_1_0/z_turn_clk_wiz_1_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_xbar_0/z_turn_xbar_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_auto_pc_0/z_turn_auto_pc_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/z_turn_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_turn'. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/z_turn.bd
# Block Designs: The module: 'z_turn' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_processing_system7_0_0/z_turn_processing_system7_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_processing_system7_0_0 || ORIG_REF_NAME==z_turn_processing_system7_0_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_xlconcat_0_0/z_turn_xlconcat_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xlconcat_0_0 || ORIG_REF_NAME==z_turn_xlconcat_0_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_ps_7_axi_periph_0/z_turn_ps_7_axi_periph_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_ps_7_axi_periph_0 || ORIG_REF_NAME==z_turn_ps_7_axi_periph_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_rst_ps_7_166M_0 || ORIG_REF_NAME==z_turn_rst_ps_7_166M_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_ps_7_axi_periph_1/z_turn_ps_7_axi_periph_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_ps_7_axi_periph_1 || ORIG_REF_NAME==z_turn_ps_7_axi_periph_1}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset1_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_1_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_3_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_3_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_util_vector_logic_0_0/z_turn_util_vector_logic_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_util_vector_logic_0_0 || ORIG_REF_NAME==z_turn_util_vector_logic_0_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_util_vector_logic_0_1/z_turn_util_vector_logic_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_util_vector_logic_0_1 || ORIG_REF_NAME==z_turn_util_vector_logic_0_1}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_util_vector_logic_1_0/z_turn_util_vector_logic_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_util_vector_logic_1_0 || ORIG_REF_NAME==z_turn_util_vector_logic_1_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_xlconcat_0_1/z_turn_xlconcat_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xlconcat_0_1 || ORIG_REF_NAME==z_turn_xlconcat_0_1}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_xlconcat_0_2/z_turn_xlconcat_0_2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xlconcat_0_2 || ORIG_REF_NAME==z_turn_xlconcat_0_2}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_xlconcat_1_0/z_turn_xlconcat_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xlconcat_1_0 || ORIG_REF_NAME==z_turn_xlconcat_1_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_0_0/z_turn_clk_wiz_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_clk_wiz_0_0 || ORIG_REF_NAME==z_turn_clk_wiz_0_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_axi_i2s_adi_0_0/z_turn_axi_i2s_adi_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_axi_i2s_adi_0_0 || ORIG_REF_NAME==z_turn_axi_i2s_adi_0_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_1_0/z_turn_clk_wiz_1_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_clk_wiz_1_0 || ORIG_REF_NAME==z_turn_clk_wiz_1_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_xbar_0/z_turn_xbar_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xbar_0 || ORIG_REF_NAME==z_turn_xbar_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_ultrasonicShiftControl_0_0/z_turn_ultrasonicShiftControl_0_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_ultrasonicShiftControl_0_0 || ORIG_REF_NAME==z_turn_ultrasonicShiftControl_0_0}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_ultrasonicAXItoPWM_0_1/z_turn_ultrasonicAXItoPWM_0_1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_ultrasonicAXItoPWM_0_1 || ORIG_REF_NAME==z_turn_ultrasonicAXItoPWM_0_1}]

# IP: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_auto_pc_0/z_turn_auto_pc_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_auto_pc_0 || ORIG_REF_NAME==z_turn_auto_pc_0}]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_processing_system7_0_0/z_turn_processing_system7_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_processing_system7_0_0 || ORIG_REF_NAME==z_turn_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_rst_ps_7_166M_0 || ORIG_REF_NAME==z_turn_rst_ps_7_166M_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_rst_ps_7_166M_0 || ORIG_REF_NAME==z_turn_rst_ps_7_166M_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset1_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset1_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_1_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_1_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_3_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_3_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_3_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_3_0}] {/U0 }]/U0 ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_0_0/z_turn_clk_wiz_0_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_clk_wiz_0_0 || ORIG_REF_NAME==z_turn_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_0_0/z_turn_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_clk_wiz_0_0 || ORIG_REF_NAME==z_turn_clk_wiz_0_0}] {/inst }]/inst ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_0_0/z_turn_clk_wiz_0_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_1_0/z_turn_clk_wiz_1_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_clk_wiz_1_0 || ORIG_REF_NAME==z_turn_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_1_0/z_turn_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_clk_wiz_1_0 || ORIG_REF_NAME==z_turn_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_1_0/z_turn_clk_wiz_1_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_xbar_0/z_turn_xbar_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_auto_pc_0/z_turn_auto_pc_0_ooc.xdc

# XDC: /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/z_turn_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'z_turn'. Do not add the DONT_TOUCH constraint.
