# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/system.xdc

# Block Designs: bd/z_turn/z_turn.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn || ORIG_REF_NAME==z_turn}]

# IP: bd/z_turn/ip/z_turn_processing_system7_0_0/z_turn_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_processing_system7_0_0 || ORIG_REF_NAME==z_turn_processing_system7_0_0}]

# IP: bd/z_turn/ip/z_turn_xlconcat_0_0/z_turn_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xlconcat_0_0 || ORIG_REF_NAME==z_turn_xlconcat_0_0}]

# IP: bd/z_turn/ip/z_turn_ps_7_axi_periph_0/z_turn_ps_7_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_ps_7_axi_periph_0 || ORIG_REF_NAME==z_turn_ps_7_axi_periph_0}]

# IP: bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_rst_ps_7_166M_0 || ORIG_REF_NAME==z_turn_rst_ps_7_166M_0}]

# IP: bd/z_turn/ip/z_turn_ps_7_axi_periph_1/z_turn_ps_7_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_ps_7_axi_periph_1 || ORIG_REF_NAME==z_turn_ps_7_axi_periph_1}]

# IP: bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset1_0}]

# IP: bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_1_0}]

# IP: bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_3_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_3_0}]

# IP: bd/z_turn/ip/z_turn_util_vector_logic_0_0/z_turn_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_util_vector_logic_0_0 || ORIG_REF_NAME==z_turn_util_vector_logic_0_0}]

# IP: bd/z_turn/ip/z_turn_util_vector_logic_0_1/z_turn_util_vector_logic_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_util_vector_logic_0_1 || ORIG_REF_NAME==z_turn_util_vector_logic_0_1}]

# IP: bd/z_turn/ip/z_turn_util_vector_logic_1_0/z_turn_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_util_vector_logic_1_0 || ORIG_REF_NAME==z_turn_util_vector_logic_1_0}]

# IP: bd/z_turn/ip/z_turn_xlconcat_0_1/z_turn_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xlconcat_0_1 || ORIG_REF_NAME==z_turn_xlconcat_0_1}]

# IP: bd/z_turn/ip/z_turn_xlconcat_0_2/z_turn_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xlconcat_0_2 || ORIG_REF_NAME==z_turn_xlconcat_0_2}]

# IP: bd/z_turn/ip/z_turn_xlconcat_1_0/z_turn_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xlconcat_1_0 || ORIG_REF_NAME==z_turn_xlconcat_1_0}]

# IP: bd/z_turn/ip/z_turn_ultrasonic_0_0/z_turn_ultrasonic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_ultrasonic_0_0 || ORIG_REF_NAME==z_turn_ultrasonic_0_0}]

# IP: bd/z_turn/ip/z_turn_clk_wiz_0_0/z_turn_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_clk_wiz_0_0 || ORIG_REF_NAME==z_turn_clk_wiz_0_0}]

# IP: bd/z_turn/ip/z_turn_xlconcat_3_0/z_turn_xlconcat_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==z_turn_xlconcat_3_0 || ORIG_REF_NAME==z_turn_xlconcat_3_0}]

# XDC: bd/z_turn/ip/z_turn_processing_system7_0_0/z_turn_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_processing_system7_0_0 || ORIG_REF_NAME==z_turn_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_rst_ps_7_166M_0 || ORIG_REF_NAME==z_turn_rst_ps_7_166M_0}] {/U0 }]/U0 ]]

# XDC: bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_rst_ps_7_166M_0 || ORIG_REF_NAME==z_turn_rst_ps_7_166M_0}] {/U0 }]/U0 ]]

# XDC: bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0_ooc.xdc

# XDC: bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset1_0}] {/U0 }]/U0 ]]

# XDC: bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset1_0}] {/U0 }]/U0 ]]

# XDC: bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0_ooc.xdc

# XDC: bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_1_0}] {/U0 }]/U0 ]]

# XDC: bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_1_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_1_0}] {/U0 }]/U0 ]]

# XDC: bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0_ooc.xdc

# XDC: bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_3_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_3_0}] {/U0 }]/U0 ]]

# XDC: bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==z_turn_proc_sys_reset_3_0 || ORIG_REF_NAME==z_turn_proc_sys_reset_3_0}] {/U0 }]/U0 ]]

# XDC: bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0_ooc.xdc

# XDC: bd/z_turn/z_turn_ooc.xdc
