# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.cache/wt [current_project]
set_property parent.project_path /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part myir.com:mys-7z020:part0:2.1 [current_project]
set_property ip_repo_paths {
  /home/niklas/xilinx/ip_repo/ultrasonicAXItoPWM_1.0
  /home/niklas/xilinx/ip_repo/ultrasonicPWMgenerator_1.0
  /home/niklas/xilinx/ip_repo/ultrasonicShiftControl_1.0
  /home/niklas/xilinx/ip_repo/myPasedArray_1.0
  /home/niklas/ledvideo
  /home/niklas/xilinx/ip_repo/deconcat_ip
  /home/niklas/xilinx/ip_repo/myI2StoPWM_1.0
  /home/niklas/zturn-stuff/Vivado/tmp/ip
  /home/niklas/zturn-doc/vivado-library/ip/axi_i2s_adi_1.2
  /home/niklas/xilinx/zturn-stuff/sdsoc/zturn-7z020/ip_repo/ultrasonic_1.0
} [current_project]
set_property ip_output_repo /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/hdl/z_turn_wrapper.v
add_files /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/z_turn.bd
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_processing_system7_0_0/z_turn_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_rst_ps_7_166M_0/z_turn_rst_ps_7_166M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset1_0/z_turn_proc_sys_reset1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_1_0/z_turn_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_proc_sys_reset_3_0/z_turn_proc_sys_reset_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_0_0/z_turn_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_0_0/z_turn_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_0_0/z_turn_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_1_0/z_turn_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_1_0/z_turn_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_clk_wiz_1_0/z_turn_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_xbar_0/z_turn_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/ip/z_turn_auto_pc_0/z_turn_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/z_turn_ooc.xdc]
set_property is_locked true [get_files /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/sources_1/bd/z_turn/z_turn.bd]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/constrs_1/new/system.xdc
set_property used_in_implementation false [get_files /home/niklas/xilinx/ultrasonic_7020_output/ultrasonic_7020.srcs/constrs_1/new/system.xdc]


synth_design -top z_turn_wrapper -part xc7z020clg400-1


write_checkpoint -force -noxdef z_turn_wrapper.dcp

catch { report_utilization -file z_turn_wrapper_utilization_synth.rpt -pb z_turn_wrapper_utilization_synth.pb }
